import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import "./globals.css";

const nanumGothic = Nanum_Gothic({
    weight: ["400", "700", "800"],
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Weekly Planner",
    description: "Generated by Myung Wan Park",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={nanumGothic.className}>{children}</body>
        </html>
    );
}
